# Generated by Django 5.0.6 on 2024-06-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard_app', '0003_alter_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
